version: "3.7"

services:
  puppet-print-pdf:
    build:
      context: .
      dockerfile: Dockerfile
    image: puppet-print-pdf
    container_name: puppet-print-pdf
    ports:
      - "3000:3000"
    volumes:
      - ./dist:/usr/src/app/dist
    command: npm run start
